import { useCallback, useEffect, useState } from 'react';
import { Check, RefreshCw } from 'lucide-react';
import { applications, completeFollowUp, followUps, refreshFollowUps, transitionApplication } from './api';
import { displayMessage } from './messages';

export function Applications() {
  const [items, setItems] = useState([]); const [reminders, setReminders] = useState([]); const [error, setError] = useState(''); const [working, setWorking] = useState(false);
  const refresh = useCallback(async () => { setError(''); try { const [nextItems, nextReminders] = await Promise.all([applications(), followUps()]); setItems(nextItems); setReminders(nextReminders); } catch (failure) { setError(displayMessage(failure)); } }, []);
  useEffect(() => { refresh(); }, [refresh]);
  const run = async action => { setWorking(true); setError(''); try { await action(); await refresh(); } catch (failure) { setError(displayMessage(failure)); } finally { setWorking(false); } };
  return <main className="app-shell applications-shell"><header className="topbar"><a className="brand" href="/dashboard"><span className="brand-mark">J</span><span>JobLens<small>career intelligence</small></span></a><nav aria-label="Workspace navigation"><a href="/dashboard">Browse</a><a href="/setup">Profile</a><a className="active" href="/applications">My list</a></nav></header><section className="applications-hero"><p className="eyebrow">Application tracker</p><h1>Keep every promising role moving.</h1><p>Save a role from Browse, update its status, and let JobLens create the next reminder from your progress.</p></section>{error && <p className="inline-error" role="alert">{error}</p>}
    <section className="surface application-panel"><div className="section-title"><div><p className="eyebrow">My applications</p><h2>{items.length ? `${items.length} role${items.length === 1 ? '' : 's'} in progress` : 'Your list is ready'}</h2></div><a className="button primary compact-action" href="/dashboard">Browse roles</a></div>{items.length ? <div className="application-list">{items.map(item => <ApplicationCard key={item.id} item={item} working={working} onTransition={status => run(() => transitionApplication(item.id, status))} />)}</div> : <p className="muted">Save a ranked role from Browse to begin tracking it here.</p>}</section>
    <section className="surface application-panel"><div className="section-title"><div><p className="eyebrow">Follow-ups</p><h2>Stay on top of the next step</h2></div><button className="button secondary compact-action" disabled={working} onClick={() => run(refreshFollowUps)}><RefreshCw size={14} className={working ? 'spin' : ''}/> Refresh reminders</button></div>{reminders.length ? <div className="followup-list">{reminders.map(reminder => <article className="followup-card" key={reminder.id}><div><span className={`followup-status ${reminder.status.toLowerCase()}`}>{reminder.status}</span><h3>{reminder.title}</h3><p>{reminder.company || 'Company not disclosed'} · {label(reminder.follow_up_type)} · due {reminder.due_date}</p></div>{reminder.status === 'OPEN' && <button className="button secondary compact-action" disabled={working} onClick={() => run(() => completeFollowUp(reminder.id))}><Check size={14}/> Complete</button>}</article>)}</div> : <p className="muted">No follow-ups yet. Updating an application to Applied, Screening, Interview, or Offer creates the appropriate reminder.</p>}</section></main>;
}

function ApplicationCard({ item, working, onTransition }) { const [next, setNext] = useState(''); return <article className="application-card"><div><span className="application-status">{item.status.replaceAll('_', ' ')}</span><h3>{item.title}</h3><p>{item.company || 'Company not disclosed'} · saved {item.applied_on}</p>{item.note && <p className="muted">{item.note}</p>}</div>{item.allowedTransitions?.length > 0 && <div className="transition-control"><label htmlFor={`transition-${item.id}`}>Move to</label><select id={`transition-${item.id}`} value={next} onChange={event => setNext(event.target.value)}><option value="">Choose status</option>{item.allowedTransitions.map(status => <option key={status} value={status}>{status.replaceAll('_', ' ')}</option>)}</select><button className="button secondary compact-action" disabled={working || !next} onClick={() => { onTransition(next); setNext(''); }}>Update</button></div>}</article>; }
function label(value) { return value?.replaceAll('_', ' ').toLowerCase() || 'follow-up'; }
